apiVersion: v1
kind: Service
metadata:
  name: {{ include "sanstrick.fullname" . }}
  labels:
    {{- include "sanstrick.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      protocol: TCP
      name: http
  selector:
    {{- include "sanstrick.selectorLabels" . | nindent 4 }}
